name: linux

on: 
  push:            # run on push events
    paths-ignore:  # but ignore everything in the docs subfolder 
      - 'docs/**'
    branches:
      - '**'
    tags:
      - '*'
  pull_request:    # run on pull requests
    paths-ignore:  # but ignore everything in the docs subfolder 
      - 'docs/**'
  schedule:
    - cron:  '5 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Cloning SAGA
      uses: actions/checkout@v2

    - name: Cloning SUMO
      uses: actions/checkout@v2
      with:
        repository: eclipse/sumo
        path: sumo
        fetch-depth: 0

    - name: Fetching SUMO tags
      run: |
        cd sumo
        git fetch --tags --force

    - name: Preparing Build System
      run: |
        sudo apt-get update
        sudo apt-get install sumo sumo-tools
#        sudo apt-get install cmake libeigen3-dev libxerces-c-dev libfox-1.6-dev libgdal-dev libproj-dev libgtest-dev libgoogle-perftools-dev libgl2ps-dev python3-dev python3-setuptools swig openjdk-8-jdk maven ccache

#    - name: Building SUMO
#      run: |
#        mkdir -p sumo/cmake-build 
#        cd sumo/cmake-build 
#        cmake ..
#        make -j4
#        sudo make install

    - name: Running Tests
      run: |
        sudo pip3 install --no-cache-dir -r requirements.txt
        gunzip tests/*.gz
        ./scenarioFromOSM.py --osm tests/wildau_osm.xml --out tests/out
