name: linux

on: 
  push:            # run on push events
    paths-ignore:  # but ignore everything in the docs subfolder 
      - 'docs/**'
    branches:
      - '**'
    tags:
      - '*'
  pull_request:    # run on pull requests
    paths-ignore:  # but ignore everything in the docs subfolder 
      - 'docs/**'
  schedule:
    - cron:  '5 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      # Allow all other matrix-jobs to continue running, even if one of the jobs fails
#      fail-fast: false
      matrix:
        build_type: [release, head]

    steps:
    - name: Cloning SAGA
      uses: actions/checkout@v2

    - name: Cloning SUMO
      if: matrix.build_type == 'head'
      uses: actions/checkout@v2
      with:
        repository: eclipse/sumo
        path: sumo
        fetch-depth: 0

    - name: Fetching SUMO tags
      if: matrix.build_type == 'head'
      run: |
        cd sumo
        git fetch --tags --force

    - name: Preparing Build System
      if: matrix.build_type == 'head'
      run: |
        sudo apt-get update
        sudo apt-get install cmake libeigen3-dev libxerces-c-dev libfox-1.6-dev libgdal-dev libproj-dev libgtest-dev libgoogle-perftools-dev libgl2ps-dev python3-dev python3-setuptools swig openjdk-8-jdk maven ccache

    - name: Building SUMO
      if: matrix.build_type == 'head'
      run: |
        mkdir -p sumo/cmake-build 
        cd sumo/cmake-build 
        cmake ..
        make -j4
        sudo make install

    - name: Installing SUMO
      if: matrix.build_type == 'release'
      run: |
        sudo add-apt-repository ppa:sumo/stable
        sudo apt-get update
        sudo apt-get install sumo sumo-tools

    - name: Running Tests
      run: |
        sudo pip3 install --no-cache-dir -r requirements.txt
        gunzip tests/*.gz
        export SUMO_HOME=/usr/share/sumo
        ./scenarioFromOSM.py --osm tests/wildau_osm.xml --out tests/out --local-defaults
