name: windows-pypi

on:
  push:            # run on push events
    paths-ignore:  # but ignore everything in the docs subfolder
      - 'docs/**'
    branches:
      - '**'
    tags:
      - '*'
  pull_request:    # run on pull requests
    paths-ignore:  # but ignore everything in the docs subfolder
      - 'docs/**'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Cloning SAGA
      uses: actions/checkout@v2

    - name: Installing PyPI SUMO
      run: |
        python -m pip install --index-url https://test.pypi.org/simple/ eclipse-sumo
        python -c "import sumo; print('SUMO_HOME=%s\\share\\sumo' % sumo.SUMO_HOME)" >> $env:GITHUB_ENV

    - name: Run tests
      run: |
        python -m pip install -r requirements.txt
        python -c "import gzip; open('wildau.xml', 'wb').write(gzip.open('tests\\wildau_osm.xml.gz').read())"
        python scenarioFromOSM.py --osm wildau.xml --out wildau --local-defaults
